config/routes.rb
Rails.application.routes.draw do
  resources :edu_subsidies
  resources :elec_subsidies
  resources :lpg_subsidies
  get 'sessions/new'

  resources :citizens

  get  '/signup',  to: 'citizens#new'
  post '/signup',  to: 'citizens#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/subsidies/lpg',     to: 'lpg_subsidies#index'
  get '/subsidies/elec',    to: 'elec_subsidies#index'
  get '/subsidies/edu',     to: 'edu_subsidies#index'

  root to: 'site#index'
  get '/about',      to: 'site#about'
end

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>Citizen Management System</strong> by <a href="https://jgthms.com">Syed Faraaz Ahmad</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>.
      </p>
    </div>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar is-danger" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item is-size-4" href="/">
            <strong>
              Citizen Management System
            </strong>
          </a>
          <span class="button navbar-burger" data-target="navbar-menu-top">
            <span></span>
            <span></span>
            <span></span>
          </span>

        </div>

        <div class="navbar-menu" id="navbar-menu-top">

          <div class="navbar-start">

          </div>

          <div class="navbar-end">
            <%= link_to "Home", root_path, class: "navbar-item" %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                Subsidies
              </a>
              <div class="navbar-dropdown is-boxed">
                <%= link_to "Education", subsidies_edu_path, class: "navbar-item" %>
                <%= link_to "Electricity", subsidies_elec_path, class: "navbar-item" %>
                <%= link_to "LPG", subsidies_lpg_path, class: "navbar-item" %>
              </div>
            </div>
            <%= link_to "About Us", about_path, class: "navbar-item" %>
            <% if logged_in? %>
              <% if current_citizen.admin %>
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link">
                    Citizens
                  </a>
                  <div class="navbar-dropdown is-boxed">
                    <%= link_to "List all", citizens_path, class: "navbar-item" %>
                    <%= link_to "Register", new_citizen_path, class: "navbar-item" %>
                  </div>
                </div>
              <% end %>
              <%= link_to "My Profile", current_citizen, class: "navbar-item" %>
              <%= link_to "Log out", logout_path, class: "navbar-item", method: :delete %>
            <% else %>
              <%= link_to "Sign In", login_path, class: "navbar-item" %>
            <% end %>
          </div>

        </div>
      </div>
    </nav>