config/routes.rb
Rails.application.routes.draw do
  resources :edu_subsidies
  resources :elec_subsidies
  resources :lpg_subsidies
  get 'sessions/new'

  resources :citizens

  get  '/signup',  to: 'citizens#new'
  post '/signup',  to: 'citizens#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/subsidies/lpg',     to: 'lpg_subsidies#index'
  get '/subsidies/elec',    to: 'elec_subsidies#index'
  get '/subsidies/edu',     to: 'edu_subsidies#index'

  root to: 'site#index'
  get '/about',      to: 'site#about'
end

app/models/lpg_subsidy.rb
class LpgSubsidy < ApplicationRecord
  has_and_belongs_to_many :citizen

  validates :citizen_id, presence: true, uniqueness: true
end

app/controllers/lpg_subsidies_controller.rb
class LpgSubsidiesController < ApplicationController
  before_action :set_lpg_subsidy, only: [:show, :edit, :update, :destroy]
  before_action :admin_logged_in

  # GET /lpg_subsidies
  def index
    @lpg_subsidies = LpgSubsidy.all
  end

  # GET /lpg_subsidies/1
  def show
  end

  # GET /lpg_subsidies/new
  def new
    @lpg_subsidy = LpgSubsidy.new
  end

  # POST /lpg_subsidies
  def create
    @lpg_subsidy = LpgSubsidy.new(lpg_subsidy_params)

    if @lpg_subsidy.save
      id = @lpg_subsidy.id
      citizen = Citizen.find(@lpg_subsidy.citizen_id)
      citizen.update_attribute(:lpg_subsidy_id, id)
      flash[:success] = 'Succesfully registered for LPG Subsidy'
      redirect_to citizen
    else
      render :new
    end
  end

  # PATCH/PUT /lpg_subsidies/1
  def update
    if @lpg_subsidy.update(lpg_subsidy_params)
      flash[:success] = 'Succesfully updated subsidy subscription'
      redirect_to @lpg_subsidy
    else
      render :edit
    end
  end

  # DELETE /lpg_subsidies/1
  def destroy
    id = @lpg_subsidy.id
    citizen = Citizen.find(@lpg_subsidy.citizen_id)
    citizen.update_attribute(:lpg_subsidy_id, nil)
    ActiveRecord::Base.connection.query("
      DELETE FROM lpg_subsidies WHERE id = #{id}
    ")
    flash[:success] = 'Succesfully unregistered from LPG Subsidy'
    redirect_to citizen
  end

  private

    def admin_logged_in
      unless admin_logged_in?
        flash[:warning] = "Please log in as admin first"
        redirect_to login_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_lpg_subsidy
      @lpg_subsidy = LpgSubsidy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lpg_subsidy_params
      params.require(:lpg_subsidy).permit(:citizen_id)
    end
end

app/helpers/lpg_subsidies_helper.rb
module LpgSubsidiesHelper
end

app/views/lpg_subsidies/_form.html.erb
<%= form_with(model: lpg_subsidy, local: true) do |form| %>
  <div class="card-content">
    <div class="content">
      <% if lpg_subsidy.errors.any? %>
        <div id="error_explanation">
          <div class="is-size-4 is-red">
            The form contains <%= pluralize(lpg_subsidy.errors.count, "error") %>.
          </div>
          <div class="tile is-parent">
            <article class="tile is-child notification is-danger">
              <div class="content">
                <ul>
                <% lpg_subsidy.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
                
              </div>
            </article>
          </div>
        </div>
      <% end %>

      <div class="field">
        <label class="label">Citizen ID</label>
        <div class="control">
          <%= form.text_field :citizen_id, class: "input" %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit "Confirm registration", class: "button is-link" %>
      </div>
    </div>
  </div>
<% end %>

app/views/lpg_subsidies/index.html.erb
<div class="container">
  <br><br><br>
  <h1 class="title is-striped is-size-1">Lpg subsidy subscribers</h1>

  <table>
    <thead>
      <tr>
        <th>UID</th>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @lpg_subsidies.each do |lpg_subsidy| %>
        <tr>
          <td><%= lpg_subsidy.citizen_id %></td>          
          <td><%= Citizen.find(lpg_subsidy.citizen_id).name %></td>  
          <td>
            <%= link_to 'Remove', 
                lpg_subsidy, 
                method: :delete, 
                data: { confirm: 'Are you sure?' }, 
                class: "button" %>      
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Subscription', new_lpg_subsidy_path, class: "button is-link" %>
</div>

app/views/lpg_subsidies/new.html.erb
<div class="container">
	<br><br><br>
	<div class="form-container">
		<div class="card">
		  <header class="card-header">
		    <p class="card-header-title">
		      New LPG subscription
		    </p>
		  </header>
			<%= render 'form', lpg_subsidy: @lpg_subsidy %>
			<footer class="card-footer">
				<%= link_to 'Back', lpg_subsidies_path, class: "card-footer-item" %>
		  </footer>
		</div>
	</div>
</div>

app/views/lpg_subsidies/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Citizen:</strong>
    <%= @lpg_subsidy.citizen %>
  </p>

  <%= link_to 'Edit', edit_lpg_subsidy_path(@lpg_subsidy) %> |
  <%= link_to 'Back', lpg_subsidies_path %>

</div>