config/routes.rb
Rails.application.routes.draw do
  resources :edu_subsidies
  resources :elec_subsidies
  resources :lpg_subsidies
  get 'sessions/new'

  resources :citizens

  get  '/signup',  to: 'citizens#new'
  post '/signup',  to: 'citizens#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/subsidies/lpg',     to: 'lpg_subsidies#index'
  get '/subsidies/elec',    to: 'elec_subsidies#index'
  get '/subsidies/edu',     to: 'edu_subsidies#index'

  root to: 'site#index'
  get '/about',      to: 'site#about'
end

app/models/elec_subsidy.rb
class ElecSubsidy < ApplicationRecord
  has_and_belongs_to_many :citizen

  validates :citizen_id, presence: true, uniqueness: true
end

app/controllers/elec_subsidies_controller.rb
class ElecSubsidiesController < ApplicationController
  before_action :set_elec_subsidy, only: [:show, :edit, :update, :destroy]
  before_action :admin_logged_in

  # GET /elec_subsidies
  def index
    @elec_subsidies = ElecSubsidy.all
  end

  # GET /elec_subsidies/1
  def show
  end

  # GET /elec_subsidies/new
  def new
    @elec_subsidy = ElecSubsidy.new
  end

  # POST /elec_subsidies
  def create
    @elec_subsidy = ElecSubsidy.new(elec_subsidy_params)

    if @elec_subsidy.save
      id = @elec_subsidy.id
      citizen = Citizen.find(@elec_subsidy.citizen_id)
      citizen.update_attribute(:elec_subsidy_id, id)
      flash[:success] = 'Succesfully registered for Electricity Subsidy'
      redirect_to citizen
    else
      render :new
    end
  end

  # PATCH/PUT /elec_subsidies/1
  def update
    if @elec_subsidy.update(elec_subsidy_params)
      flash[:success] = 'Succesfully updated subsidy subscription'
      redirect_to @elec_subsidy
    else
      render :edit
    end
  end

  # DELETE /elec_subsidies/1
  def destroy
    id = @elec_subsidy.id
    citizen = Citizen.find(@elec_subsidy.citizen_id)
    citizen.update_attribute(:elec_subsidy_id, nil)
    ActiveRecord::Base.connection.query("
      DELETE FROM elec_subsidies WHERE id = #{id}
    ")
    flash[:success] = 'Succesfully unregistered from Electricity subsidy'
    redirect_to citizen
  end

  private
    def admin_logged_in
      unless admin_logged_in?
        flash[:warning] = "Please log in as admin first"
        redirect_to login_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_elec_subsidy
      @elec_subsidy = ElecSubsidy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elec_subsidy_params
      params.require(:elec_subsidy).permit(:citizen_id)
    end
end

app/helpers/elec_subsidies_helper.rb
module ElecSubsidiesHelper
end

app/views/elec_subsidies/_form.html.erb
<%= form_with(model: elec_subsidy, local: true) do |form| %>
  <div class="card-content">
    <div class="content">
      <% if elec_subsidy.errors.any? %>
        <div id="error_explanation">
          <div class="is-size-4 is-red">
            The form contains <%= pluralize(elec_subsidy.errors.count, "error") %>.
          </div>
          <div class="tile is-parent">
            <article class="tile is-child notification is-danger">
              <div class="content">
                <ul>
                <% elec_subsidy.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
                
              </div>
            </article>
          </div>
        </div>
      <% end %>

      <div class="field">
        <label class="label">Citizen ID</label>
        <div class="control">
          <%= form.text_field :citizen_id, class: "input" %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit "Confirm registration", class: "button is-link" %>
      </div>
    </div>
  </div>
<% end %>

app/views/elec_subsidies/index.html.erb
<div class="container">
  <br><br><br>
  <h1 class="title is-striped is-size-1">Electricity subsidy subscribers</h1>

  <table>
    <thead>
      <tr>
        <th>UID</th>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @elec_subsidies.each do |elec_subsidy| %>
        <tr>
          <td><%= elec_subsidy.citizen_id %></td>
          <td><%= Citizen.find(elec_subsidy.citizen_id).name %></td>          
          <td>
            <%= link_to 'Remove', 
                elec_subsidy, 
                method: :delete, 
                data: { confirm: 'Are you sure?' }, 
                class: "button" %>      
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Subscription', new_elec_subsidy_path, class: "button is-link" %>
</div>

app/views/elec_subsidies/new.html.erb
<div class="container">
	<br><br><br>
	<div class="form-container">
		<div class="card">
		  <header class="card-header">
		    <p class="card-header-title">
		      New Electricity subscription
		    </p>
		  </header>
			<%= render 'form', elec_subsidy: @elec_subsidy %>
			<footer class="card-footer">
				<%= link_to 'Back', elec_subsidies_path, class: "card-footer-item" %>
		  </footer>
		</div>
	</div>
</div>

app/views/elec_subsidies/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Citizen:</strong>
    <%= @elec_subsidy.citizen %>
  </p>

  <%= link_to 'Edit', edit_elec_subsidy_path(@elec_subsidy) %> |
  <%= link_to 'Back', elec_subsidies_path %>

</div>